# action.yml
name: 'SSH Command'
description: 'Run a command on a remote server via ssh'

inputs:
  HOST:
    description: '3.108.61.209'
    required: true
  PORT:
    description: '22'
    required: false
    default: 22
  USER:
    description: 'ubuntu'
    required: true
  PRIVATE_SSH_KEY:
    description: 'private ssh key registered on the server'
    required: true
  COMMAND:
    description: 'command to be executed'
    required: false
    default: 'echo Hello World!'
    uses: D3rHase/ssh-command-action@{version}
with:
  HOST: ${{secrets.HOST}}                             # Remote server address / ip - Required: true
  PORT: ${{secrets.PORT}}                             # Remote server port -  Default: 22 - Required: false
  USER: ${{secrets.USER}}                             # Remote server user - Required: true
  PRIVATE_SSH_KEY: ${{secrets.PRIVATE_SSH_KEY}}       # Private ssh key registered on the remote server - Required: true
  COMMAND: ${{secrets.COMMAND}}   

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.HOST }}
    - ${{ inputs.PORT }}
    - ${{ inputs.USER }}
    - ${{ inputs.PRIVATE_SSH_KEY }}
    - ${{ inputs.COMMAND }}

branding:
  icon: 'terminal'
  color: 'yellow'
