name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
      with:
        script: |
          cd /opt/socialswag-lambda-automation/
          echo ${{ secrets.KEY }} | sudo -S git pull https://github.com/Ram5535/CICD-pipeline.git
          
